public enum TipoToken {
    LEFT_PAREN, RIGHT_PAREN, COMMA, SEMICOLON,
    MINUS, PLUS, SLASH, STAR, MOD,

    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    STRING,
    IDENTIFIER, NUMBER,

    NULL,

    EOF
}